VERSION 4.00
Begin VB.Form Form2 
   Caption         =   "Form2"
   ClientHeight    =   5940
   ClientLeft      =   1140
   ClientTop       =   1515
   ClientWidth     =   7305
   Height          =   6345
   Left            =   1080
   LinkTopic       =   "Form2"
   ScaleHeight     =   5940
   ScaleWidth      =   7305
   Top             =   1170
   Width           =   7425
End
Attribute VB_Name = "Form2"
Attribute VB_Creatable = False
Attribute VB_Exposed = False
Option Explicit

